In [ ]:
import numpy as np
X=np.random.random((1000,1000))
Y=np.random.random((1000,1000))


In [ ]:
def mul_loops(A,B):
    C=np.zeros((A.shape[0],B.shape[1]))
    for i in range(A.shape[1]):
        for j in range(B.shape[0]):
            C[i,j]=A[i,j]*B[j,i]
    return  C

In [ ]:
def mul_vector(A,B):
    return  A @ B

In [18]:
%timeit mul_vector(X,Y)

24.6 s ± 2.2 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit mul_loops(X,Y)

In [2]:
from matplotlib import pyplot as plt
import numpy as np
plt.plot([3,5,6,2,1])
plt.show()

<Figure size 640x480 with 1 Axes>

In [4]:
a=np.array([1,2,3])

In [5]:
type(a)


numpy.ndarray

In [9]:
x=np.zeros((3,4))
type(x.dtype)
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
y=np.ones((3,4),dtype=np.int16)

In [20]:
# type(y.dtype)
print(x.dtype)
print(y.dtype)
# print(y)
# print(y.shape)

float64
int16


In [21]:
np.full((3,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [24]:
np.arange(10,110,10)


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [25]:
np.arange(0,20,.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [27]:
x=[
    [
        [1],
        [1],
        [1],
        [1]
    ],
    
    [
        [1],
        [1],
        [1],
        [1]
    ]
]


(2, 4, 1)

In [28]:
np.array(x).shape

(2, 4, 1)

In [30]:
xx=np.array(x)
print(xx.shape)

(2, 4, 1)


In [32]:
print(xx)

[[[1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]]]


In [33]:
np.array(xx)

array([[[1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1]]])

In [38]:
np.zeros((2,2,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [39]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [41]:
xx.itemsize

8

In [53]:
aa=np.arange(16)

In [47]:
print(aa)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [52]:
bb=aa.reshape(16,1)
print(bb)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [55]:
aa[2:5]

array([2, 3, 4])

In [56]:
print(aa[2::2])

[ 2  4  6  8 10 12 14]


In [61]:
print(aa[8::-1])

[8 7 6 5 4 3 2 1 0]


In [62]:
aa[::2]=-1

In [63]:
aa

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1, 13, -1, 15])

In [66]:
a=np.array([1,2,5,7,8])
a_slice=a[1:5] # array([2, 5, 7, 8])
a_slice[1]=1000
print(a)

[   1    2 1000    7    8]


In [67]:
a_slice

array([   2, 1000,    7,    8])

In [69]:
a

array([   1,    2, 1000,    7,    8])

In [70]:
aslice=a[2:6].copy()

In [71]:
aslice

array([1000,    7,    8])

In [77]:
x=np.random.rand(5,5,5)

In [78]:
x

array([[[0.1354564 , 0.22687805, 0.75802321, 0.28709307, 0.67485878],
        [0.78822111, 0.30866206, 0.57545466, 0.3117367 , 0.59526648],
        [0.39993926, 0.92834019, 0.62983392, 0.25699036, 0.60043559],
        [0.20373637, 0.9423582 , 0.20155119, 0.13391331, 0.89031405],
        [0.80968982, 0.68232099, 0.28800065, 0.04019812, 0.19161639]],

       [[0.54064888, 0.50760037, 0.36019035, 0.28030717, 0.51399081],
        [0.68912699, 0.06961287, 0.30637712, 0.74336864, 0.48594187],
        [0.89409145, 0.95557928, 0.1672339 , 0.70589939, 0.60831054],
        [0.53543401, 0.29854282, 0.84052618, 0.11013812, 0.07919644],
        [0.99945531, 0.08294667, 0.95162282, 0.22213392, 0.35809035]],

       [[0.03815605, 0.8154634 , 0.96864299, 0.71608469, 0.92598876],
        [0.48453233, 0.098893  , 0.8815564 , 0.62430117, 0.07671017],
        [0.48236474, 0.64073321, 0.97504508, 0.7344672 , 0.93429258],
        [0.59583864, 0.99637228, 0.18781715, 0.36590756, 0.83121326],
        [0.44864

In [80]:
x[0:2,0:2,0:2]

array([[[0.1354564 , 0.22687805],
        [0.78822111, 0.30866206]],

       [[0.54064888, 0.50760037],
        [0.68912699, 0.06961287]]])

In [81]:
rows_on=np.array([True,False,True],dtype=bool)

In [82]:
rows_on

array([ True, False,  True])

In [84]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [85]:
np.linspace(0,5/3,6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [86]:
np.random.rand(2,3)

array([[0.31853621, 0.04715997, 0.20288278],
       [0.50230953, 0.64388472, 0.47478796]])

In [90]:
xxx=np.empty((2,3))

In [95]:
xxx.ndim
xxx.shape
xxx.size
xxx.dtype
xxx.itemsize

8

In [96]:
a=np.arange(6)

In [99]:
ar=a.reshape(2,3)
print(ar)

[[0 1 2]
 [3 4 5]]


In [101]:
a=np.arange(12).reshape(3,4)
print(a)
rows_on=np.array([True,False,True])
a[rows_on,:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [104]:
a=np.array([[-2.5,3.1,7],[10,11,12]])
print(a)

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]


In [105]:
print("mean =",a.mean())
print("min =",a.min())
print("max =",a.max())
print("sum =",a.sum())
print("prod =",a.prod())
print("std =",a.std())
print("var =",a.var())

mean = 6.766666666666667
min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.084835843520964
var = 25.855555555555554


In [106]:
m1=np.arange(6).reshape(2,3)

In [107]:
m1

array([[0, 1, 2],
       [3, 4, 5]])

In [108]:
m1.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [109]:
coeffs=np.array([[2,6],[5,3]])
depvars=np.array([6,-9])

In [112]:
sol=np.linalg.solve(coeffs,depvars)

In [ ]:
sol

In [116]:
coeffs.dot(sol),depvars

(array([ 6., -9.]), array([ 6, -9]))

In [3]:
import numpy as np
Q = np.array( [ [ [1, 3 ] ] ] )
P = np.array( [ 5 ] )

S = Q + P

print(S)

[[[6 8]]]


In [6]:
X_broad=np.ones((3,3))
print(X_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
Y_broad = np.arange(3)
print(Y_broad)

[0 1 2]


In [9]:
Z_broad=X_broad+Y_broad

In [10]:
print(Z_broad)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [3]:
import numpy as np

M = np.arange(6).reshape(2, 3)

print(M)

[[0 1 2]
 [3 4 5]]


In [20]:
print("Transpose = ", M.T)

Transpose =  [[0 3]
 [1 4]
 [2 5]]


In [29]:
N = np.arange(6).reshape(3, 2)
print(N)

[[0 1]
 [2 3]
 [4 5]]


In [39]:
print("Transpose = ", N.T)

Transpose =  [[0 2 4]
 [1 3 5]]


In [5]:
%timeit x=1

14.1 ns ± 0.13 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [7]:
sample_list = [1,2,3]
list_array = np.array(sample_list)
tup = (1,2,3)
my_tup_array = np.array(tup)
print(my_tup_array) 

[1 2 3]


In [14]:
def multiply_loops(A, B):
    c=np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for k in range(B.shape[1]):
            c[i,k] = 0
            for j in range(B.shape[0]):
                n = A[i,j] * B[j,k]
                c[i,k] += n
    return c
def multiply_vector(A, B):
     return A @ B

X = np.random.random((100, 100))
Y = np.random.random((100, 100))
    
%timeit multiply_loops(X, Y)
%timeit multiply_vector(X, Y)

988 ms ± 20.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
146 µs ± 43.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [99]:
tup_dim = (3, 4)
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)
print(my_zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [101]:
my_seven_array = np.full( tup_dim, 7, dtype=np.int16)
print(my_seven_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [46]:

my_ones_array = np.ones( tup_dim, dtype=np.int16)

my_identity_array = np.identity(3, dtype=np.float64)

In [127]:
my_identity_array = np.identity(4, dtype=np.float64)

In [128]:
my_identity_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
my_ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [6]:
import numpy as np
my_rand_array = np.random.rand(3,4)
=(3,4)

In [5]:
my_rand_array

array([[0.21594312, 0.08467626, 0.57789807, 0.81177678],
       [0.94702539, 0.48816172, 0.31516589, 0.37902865],
       [0.87620198, 0.30031901, 0.48531804, 0.60882898]])

In [7]:
my_uninitialized_array = np.empty(tup_dim)

In [8]:
my_uninitialized_array

array([[0.21594312, 0.08467626, 0.57789807, 0.81177678],
       [0.94702539, 0.48816172, 0.31516589, 0.37902865],
       [0.87620198, 0.30031901, 0.48531804, 0.60882898]])

In [85]:
# stock price prediction
stock_prices=[1.0,1.1,1.1,1.2,1.25,1.3,1.4]
windows_size=4
x1=[1.0,1.1,1.1,1.2]
y1=1.25
x2=[1.1,1.1,1.2,1.25]
y2=1.3
import numpy as np
def prepareXy(stock_prices,barch_size):
    # X is basically array of arrays
    # y is basically an array
#     X=np.split(stock_prices, barch_size)
    X = np.array_split(stock_prices, barch_size)
#     print(len(X))
    return X, len(X)



In [86]:
prepareXy(stock_prices,windows_size)


([array([1. , 1.1]), array([1.1, 1.2]), array([1.25, 1.3 ]), array([1.4])], 4)

In [22]:
my_range_array = np.arange(10,30,5)
my_range_array

array([10, 15, 20, 25])

In [23]:
my_spaced_array = np.linspace( 0,5/3,6)

In [24]:
my_spaced_array

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [34]:
array_A = np.array([ [3,4,6], [0,8,1] ])

In [35]:
array_A

array([[3, 4, 6],
       [0, 8, 1]])

In [41]:
print(array_A.ndim)
print(array_A.shape)
print(array_A.size)
print(array_A.dtype)
print(array_A.itemsize)


2
(2, 3)
6
int64
8


In [42]:
my_array=np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])

In [43]:
my_array

array([[ 1,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 14, 16]])

In [53]:
print(my_array.ndim)

2


In [93]:
name_arr, address_arr, zipcode_arr = np.loadtxt('my_file.txt', 
                                                skiprows=2, unpack=True)

OSError: my_file.txt not found.

In [100]:
import numpy as np
import os
#name_arr, address_arr, zipcode_arr = np.loadtxt('my_file.txt', skiprows=2, unpack=True)
import pandas as pd
# defining housing.csv file path
HOUSING_PATH =  '/cxldata/datasets/project/housing'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

In [106]:
FILE =  '/cxldata/datasets/project/housing/housing.csv'
def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8')}, delimiter=',', skiprows=1, unpack=True)

In [105]:
housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr = load_housing_data()

ValueError: could not convert string to float: 

In [103]:
longitude_arr

array([-122.23, -122.22, -122.24, ..., -121.22, -121.32, -121.24])

In [ ]:
import numpy as np
import os
import pandas as pd
# defining housing.csv file path
HOUSING_PATH =  '/cxldata/datasets/project/housing'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)



In [25]:
import numpy as np
import os
import pandas as pd
# defining housing.csv file path
HOUSING_PATH =  '/cxldata/datasets/project/housing'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)




In [10]:
FILE="housing_short.csv"

In [11]:
def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

In [12]:
longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

In [13]:
print(median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [26]:
import numpy as np
import os
import pandas as pd
FILE = os.path.join(HOUSING_PATH, 'housing.csv')
def load_housing_dataset(file =FILE ):
    return np.genfromtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skip_header=1, filling_values = 99999999, unpack=False)

# my_arr = np.genfromtxt('/cxldata/datasets/project/housing/housing.csv', skip_header=2, filling_values=9999999)

In [27]:
result_arr=load_housing_dataset()

In [30]:
print(result_arr.size)

20640


In [31]:
print(result_arr)

[(-122.23, 37.88, 41.,  880.,  129.,  322.,  126., 8.3252, 452600., b'NEAR BAY')
 (-122.22, 37.86, 21., 7099., 1106., 2401., 1138., 8.3014, 358500., b'NEAR BAY')
 (-122.24, 37.85, 52., 1467.,  190.,  496.,  177., 7.2574, 352100., b'NEAR BAY')
 ...
 (-121.22, 39.43, 17., 2254.,  485., 1007.,  433., 1.7   ,  92300., b'INLAND')
 (-121.32, 39.43, 18., 1860.,  409.,  741.,  349., 1.8672,  84700., b'INLAND')
 (-121.24, 39.37, 16., 2785.,  616., 1387.,  530., 2.3886,  89400., b'INLAND')]


In [42]:
import numpy as np
my_arr=np.array([[1,2],[3,4],[5,6],[7,8]])

In [43]:
print(my_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
my_arr.resize((3,4))

In [15]:
import numpy as np
my_first_arr=np.array([1,2,3,4,5,6,7,8])
my_new_arr=my_first_arr.reshape(2,4)
print(my_new_arr)
print(my_first_arr)



[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [17]:
import numpy as np
my_second_arr=np.array([0,1,2,3,4,5,6,7,8])
my_updated_arr=my_second_arr.reshape(-1,3)
print(my_updated_arr)
print(my_second_arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [27]:
import numpy as np
arr = np.array([1, 10, 31, 2, 18, 9, 22])

print(arr[1])

10


In [28]:
part_arr = arr[2 : 5]

In [30]:
print(part_arr)


[31  2 18]


In [31]:
skip_arr = arr[1: :2]
print(skip_arr)

[10  2  9]


In [12]:
import numpy as np
my_orig_arr = np.array([1, 15, 3, 9, 26, 7, 89, 12])
my_rev_arr = my_orig_arr[ : : -1]
print(my_rev_arr)

my_orig_arr2 = np.array([2, 9, 17, 13, 1, 4, 20, 57])
my_orig_arr2[2 : 5] = -6

print(my_orig_arr2)

[12 89  7 26  9  3 15  1]
[ 2  9 -6 -6 -6  4 20 57]


In [2]:
import numpy as np
apple = np.array([1, 8, 23, 3, 18, 91, 7, 15])
apple_slice=apple[1:4]
print(apple_slice)
apple_slice_new=apple[2 : 5].copy()
apple_slice_new[1] = 222222
print(apple_slice_new)
print(apple)

[ 8 23  3]
[    23 222222     18]
[ 1  8 23  3 18 91  7 15]


In [28]:
from  sklearn.datasets import load_sample_image
china = load_sample_image("china.jpg")
image = china[150:220, 130:250]
portion = china[120:250,110:230]
print(portion)

[[[ 62  61  56]
  [ 25  22  15]
  [ 28  29  21]
  ...
  [ 21  27  23]
  [ 25  25  23]
  [ 18  13  10]]

 [[ 33  34  29]
  [ 24  24  16]
  [ 38  39  33]
  ...
  [ 21  25  24]
  [ 26  24  25]
  [ 29  23  25]]

 [[  3   3   1]
  [ 15  14  10]
  [ 29  30  25]
  ...
  [ 30  31  33]
  [ 18  16  19]
  [ 20  15  19]]

 ...

 [[ 35  32  25]
  [ 32  32  24]
  [ 28  22  22]
  ...
  [ 70  81  85]
  [ 76  88  86]
  [ 93  86  68]]

 [[ 52  51  33]
  [ 52  46  20]
  [ 50  43  25]
  ...
  [ 72  76  88]
  [ 94  99 105]
  [122 104  84]]

 [[ 58  60  39]
  [ 63  62  34]
  [ 65  67  46]
  ...
  [ 90 104 105]
  [103 119 119]
  [127 126 108]]]


In [44]:
import numpy as np
from sklearn.datasets import load_sample_image
china = load_sample_image("china.jpg")
china.reshape(427, 640, 3)
image = china[150:220, 130:250]
image.shape
height, width, channels = image.shape 
image_grayscale = image.mean(axis=2).astype(np.float32)
image_grayscale.shape
images=image_grayscale.reshape(1, height, width, 1)
images.shape

(1, 70, 120, 1)

In [3]:
import numpy as np
my_multi_arr = np.arange(20).reshape(4,5)
#  Extract values from row index numbers 2 to 4 and from column index numbers 2 to 5,
my_multi_arr_portion = my_multi_arr[2:4,2:5]
print(my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


In [11]:
# Revel- Convert multi dim arr to 1D
my_2d_arr=np.arange(20)
my_2d_arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
# Revel- Convert multi dim arr to 1D
my_2d_arr = np.arange(20).reshape(4,5)
my_2d_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
my_1d_arr = my_2d_arr.ravel()
print(my_1d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [1]:
# Math Operations in numpy
import numpy as np
a = np.array([ 20, 30, 40, 50])
b = np.arange(4)
c=a+b
c

array([20, 31, 42, 53])

In [2]:
print(a)
print(b)
print(c)

[20 30 40 50]
[0 1 2 3]
[20 31 42 53]


In [3]:
import numpy as np
d = np.array([ 20, 30, 40, 50])
e = np.arange(4)


In [4]:
print(d)
print(e)


[20 30 40 50]
[0 1 2 3]


In [6]:
f=d-e
print(f)

[20 29 38 47]


In [9]:
import numpy as np
a_arr = np.array([60,70,80,90])
b_arr = np.arange(4)
c_arr=a_arr+b_arr
print(c_arr)


[60 71 82 93]


In [10]:
d_arr = np.array([60,70,80,90])
e_arr = np.arange(4)
f_arr=d_arr-e_arr
print(f_arr)

[60 69 78 87]


In [28]:
# Element product
import numpy as np
A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )
M_arr= A_arr*B_arr
print(M_arr)
    

[[10 72]
 [ 4 42]]


In [29]:
# Dot Product
C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )
P_arr = np.dot(C_arr,D_arr)
print(P_arr)


[[19 94]
 [15 74]]


In [46]:
# Division and Modulus
import numpy as np
R = np.array( [ 20, 30, 40, 50] )
S = np.arange( 1, 5 )

T = R / S 

print(R)
#array([ 20, 30, 40, 50 ])

print(S)
#array( [ 1, 2, 3, 4 ] )

print(T)


[20 30 40 50]
[1 2 3 4]
[20.         15.         13.33333333 12.5       ]


In [47]:
import numpy as np
Ri = np.array( [ 20, 30, 40, 50] )
Si = np.arange( 1, 5 )

Ti = Ri // Si 

print(Ri)
# array([ 20, 30, 40, 50 ])

print(Si)
# array( [ 1, 2, 3, 4 ] )

print(Ti)


[20 30 40 50]
[1 2 3 4]
[20 15 13 12]


In [48]:
import numpy as np
Rm = np.array( [ 20, 30, 40, 50] )
Sm = np.arange( 1, 5 )

Tm = Rm % Sm 

print(Rm)
# array([ 20, 30, 40, 50 ])

print(Sm)
# array( [ 1, 2, 3, 4 ] )

print(Tm)


[20 30 40 50]
[1 2 3 4]
[0 0 1 2]


In [50]:
R_div = np.array([ [ 25,65], [40, 14] ])
S_div = np.array([ [2, 10], [4, 5] ] )
T_div = R_div  / S_div
print(T_div)

[[12.5  6.5]
 [10.   2.8]]


In [51]:
R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array([ [2, 10], [8, 3] ] )
T_int_div=R_int_div//S_int_div
print(T_int_div)

[[12  6]
 [ 5 23]]


In [54]:
R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array([ [2, 10], [8, 3] ] )
T_mod = R_mod  % S_mod
print(T_mod)

[[0 5]
 [0 1]]


In [73]:
R_exp = np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )
T_exp=R_exp ** S_exp
print(T_exp)

[[  16 1024]
 [  81 1024]]


In [82]:
import numpy as np
m = np.array( [ 20, -5, 30, 40] )

m < [15, 16, 35, 36]


array([False,  True,  True, False])

In [83]:
m[m<25]

array([20, -5])

In [98]:
U = np.array([ [ 22, 45], [90, 4 ]])
# U=U[U<45]
print(U[U<45])

[22  4]


In [99]:
# import numpy as np
# U = np.array([ [22,45], [90,4]])
# print(U[U<45])

[22  4]


In [106]:
import numpy as np
X_stat=np.array( [ [ 1, 2, 3], [ 4, -5, 6] ])
print("mean = ", X_stat.mean())
print("Variance = ", X_stat.var())
print("Standard Deviation = ", X_stat.std())
print("min = ", X_stat.min())
print("max = ", X_stat.max())
print("sum = ", X_stat.sum())
print("prod = ", X_stat.prod())


mean =  1.8333333333333333
Variance =  11.805555555555557
Standard Deviation =  3.435921354681384
min =  -5
max =  6
sum =  11
prod =  -720


In [119]:
import numpy as np
Z=np.arange(18).reshape(2,3,3)

print(Z)
print( Z.sum(axis=2))



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[ 3 12 21]
 [30 39 48]]


In [140]:
import numpy as np
N = np.arange(6).reshape(3,2)
print(N)
print("Transpose = ", N.T)

[[0 1]
 [2 3]
 [4 5]]
Transpose =  [[0 2 4]
 [1 3 5]]


In [128]:
print("Transpose = ", N.T)

Transpose =  [[0 3]
 [1 4]
 [2 5]]


In [ ]:
import numpy as np
X_broad = np.ones()
